### ISSUE TITLE
ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by doom-fr** [jetsonhacks/installTensorFlowJetsonTX#10]
I have installed this wheel https://github.com/jetsonhacks/installTensorFlowJetsonTX/raw/master/TX2/tensorflow-1.3.0-cp35-cp35m-linux_aarch64.whl on a Jetson TX2

And I have this error :

```
 import tensorflow as tf
  File "/home/nvidia/.local/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/nvidia/.local/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/nvidia/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/nvidia/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/nvidia/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/nvidia/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

```

It seems that I have Cuda 9 not Cuda 8 :
```
ls /usr/local/cuda*
/usr/local/cuda:
bin  extras   lib64    nvml  README   share    tools
doc  include  LICENSE  nvvm  samples  targets  version.txt

/usr/local/cuda-9.0:
bin  extras   lib64    nvml  README   share    tools
doc  include  LICENSE  nvvm  samples  targets  version.txt

```

Is there a simple workaround ?

Thx.

**Comment by jetsonhacks** [comment]
There is no easy workaround. However, NVIDIA now has an official version that you can use: https://devtalk.nvidia.com/default/topic/1038957/jetson-tx2/tensorflow-for-jetson-tx2-/
